[workspace]
members = [
    "catalogs/postgres",
    "catalogs/sqlite",
    "indexlake",
    "integration-tests",
    "integrations/datafusion",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/lewiszlw/indexlake"
license = "MIT"
repository = "https://github.com/lewiszlw/indexlake"

[workspace.dependencies]
indexlake = { path = "indexlake" }
indexlake-catalog-postgres = { path = "catalogs/postgres" }
indexlake-catalog-sqlite = { path = "catalogs/sqlite" }
indexlake-datafusion = { path = "integrations/datafusion" }

arrow = "55"
async-trait = "0.1"
bb8 = "0.9"
bb8-postgres = "0.9"
comfy-table = "7.0"
datafusion = "47"
hex = "0.4"
opendal = "0.53"
rstest = { git = "https://github.com/la10736/rstest.git", rev = "2e28584b03b88edf3c1638e2e28dc2474df92811"}
rusqlite = "0.36"
tokio = "1"
url = "2.5"
uuid = "1.17"