[package]
name = "indexlake-index-hash"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
indexlake = { workspace = true }

arrow = { workspace = true }