[package]
name = "indexlake"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "An experimental table format with extensible index support."

[dependencies]
arrow = { workspace = true }
async-trait = { workspace = true }
comfy-table = { workspace = true }
opendal = { workspace = true, features = ["services-fs", "services-s3"] }
url = { workspace = true }