[package]
name = "indexlake"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
description = "An experimental table format with extensible index support."

[dependencies]
async-trait = { workspace = true }
arrow = { workspace = true }