[package]
name = "indexlake-integration-tests"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
indexlake = { workspace = true }
indexlake-catalog-sqlite = { workspace = true }

rusqlite = { workspace = true, features = ["bundled"] }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4"] }